baseurl = "https://aurelien-giroux.github.io/blog-finance/"
languageCode = "fr-fr"
locale = "fr-fr"
title = "Aurélien Giroux"
defaultContentLanguage = "fr"
hasCJKLanguage = false
enableRobotsTXT = true
timeZone = "Europe/Paris"

[pagination]
    pagerSize = 8
